In [1]:
import numpy as np

In [3]:
my_list=list(range(100))
a=np.array(my_list)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
array_2d=[[1,2,3],[2,3,4],[5,6,7]]
array_2d

[[1, 2, 3], [2, 3, 4], [5, 6, 7]]

In [6]:
arr_np_2d=np.array(array_2d)

In [7]:
arr_np_2d

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [8]:
#zeroes and #ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
#linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#random numbers [0 1] uniformely distributed

np.random.rand(3)

In [23]:
np.random.rand(3)

array([0.55734028, 0.9202394 , 0.23591982])

In [24]:
np.random.randn(3)#normally distributed

array([ 0.77576317, -0.79072204,  0.56549514])

In [25]:
np.random.randn(3,3)

array([[-0.49521818,  0.07333257, -0.22969243],
       [-0.44352009, -1.88416589,  0.37657546],
       [ 1.56874508, -0.29689397, -0.87189007]])

In [27]:
np.random.randint(10,100,10)

array([61, 14, 81, 50, 23, 19, 17, 89, 81, 15])

In [28]:
#array attributes

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
a=np.random.randint(1,20,9)

In [35]:
a=a.reshape(3,3)

In [36]:
a

array([[14,  2,  6],
       [ 8,  3,  5],
       [19,  4,  1]])

In [39]:
a.max(),a.min(),a.argmax(),a.argmin()

(19, 1, 6, 8)

In [40]:
a[0][0]

14

In [41]:
b=a.reshape(9,1)

In [42]:
b

array([[14],
       [ 2],
       [ 6],
       [ 8],
       [ 3],
       [ 5],
       [19],
       [ 4],
       [ 1]])

In [43]:
#Airthmetic Operation


In [45]:
a

array([[14,  2,  6],
       [ 8,  3,  5],
       [19,  4,  1]])

In [47]:
a*2

array([[28,  4, 12],
       [16,  6, 10],
       [38,  8,  2]])

In [48]:
a=np.sqrt(a)

In [49]:
a

array([[3.74165739, 1.41421356, 2.44948974],
       [2.82842712, 1.73205081, 2.23606798],
       [4.35889894, 2.        , 1.        ]])

In [50]:
np.exp(a)

array([[42.16782067,  4.11325038, 11.58243519],
       [16.91882868,  5.65223367,  9.35646902],
       [78.17101632,  7.3890561 ,  2.71828183]])

In [51]:
np.sin(a)

array([[-0.5646959 ,  0.98776595,  0.63815764],
       [ 0.30807174,  0.98702664,  0.78674913],
       [-0.93817027,  0.90929743,  0.84147098]])

In [52]:
np.log(a)

array([[1.31952866, 0.34657359, 0.89587973],
       [1.03972077, 0.54930614, 0.80471896],
       [1.47221949, 0.69314718, 0.        ]])

In [56]:
#element wise operation
a**2

array([[14.,  2.,  6.],
       [ 8.,  3.,  5.],
       [19.,  4.,  1.]])

In [54]:
a*a

array([[14.,  2.,  6.],
       [ 8.,  3.,  5.],
       [19.,  4.,  1.]])

In [55]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2.4178672828095276