In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])

In [3]:
a


array([1, 2, 3, 4])

In [4]:
b=np.array([[1,2,3],[1,2,3]])

In [5]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
b.shape

(2, 3)

In [7]:
a.shape

(4,)

In [8]:
b.dtype

dtype('int64')

In [9]:
b.ndim

2

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
c=range(100000)

In [14]:
c
%timeit

In [15]:
%timeit [i**3 for i in c]

36.8 ms ± 2.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
c_numpy=np.arange(11000000)

In [17]:
%timeit c_numpy**3

178 ms ± 61.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
l1=range(1000)
l2 =[i**2 for i in range(10000)]

In [19]:
%timeit list(map(lambda x,y:x*y,l1,l2))

129 µs ± 4.93 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
np.zeros(3)

In [ ]:
np.ones((3,2))

In [ ]:
np.eye(4)

In [ ]:
np.full((3,3),2.2,dtype=np.int)

In [35]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [37]:
v=np.array([1,2,3])

In [38]:
v

array([1, 2, 3])

In [44]:
np.tile(v,(5,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [45]:
50*np.random.random()+2

36.72714644316898

In [46]:
np.random.random([2,2])

array([[7.61309971e-01, 1.89626876e-01],
       [4.80983811e-04, 3.69578510e-01]])

In [49]:
#lecture 2
a=np.linspace(1,50,100)

In [48]:
a

array([  1.        ,   6.04040404,  11.08080808,  16.12121212,
        21.16161616,  26.2020202 ,  31.24242424,  36.28282828,
        41.32323232,  46.36363636,  51.4040404 ,  56.44444444,
        61.48484848,  66.52525253,  71.56565657,  76.60606061,
        81.64646465,  86.68686869,  91.72727273,  96.76767677,
       101.80808081, 106.84848485, 111.88888889, 116.92929293,
       121.96969697, 127.01010101, 132.05050505, 137.09090909,
       142.13131313, 147.17171717, 152.21212121, 157.25252525,
       162.29292929, 167.33333333, 172.37373737, 177.41414141,
       182.45454545, 187.49494949, 192.53535354, 197.57575758,
       202.61616162, 207.65656566, 212.6969697 , 217.73737374,
       222.77777778, 227.81818182, 232.85858586, 237.8989899 ,
       242.93939394, 247.97979798, 253.02020202, 258.06060606,
       263.1010101 , 268.14141414, 273.18181818, 278.22222222,
       283.26262626, 288.3030303 , 293.34343434, 298.38383838,
       303.42424242, 308.46464646, 313.50505051, 318.54

In [50]:
a.itemsize

8

In [51]:
np.arange(18).shape

(18,)

In [52]:
b=np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [54]:
b.shape


(2, 3)

In [55]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [56]:
a=np.array(range(20))

In [57]:
a[0]

0

In [59]:
a[[2,4,6]]#pass it as a buundle list

array([2, 4, 6])

In [60]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [61]:
a[2:6]

array([2, 3, 4, 5])

In [62]:
a[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
a=np.array([[1,2,3],[2,5,6],[7,8,9]])

In [64]:
a[2,2]

9

In [23]:
a[(a>2)&(a<5)]

array([3, 4])

In [24]:
b=a


In [25]:
b[0]=11

In [26]:
a

array([11,  2,  3,  4])

In [27]:
# bcoz it save it in same memory location


In [28]:
np.shares_memory(a,b)

True

In [29]:
a=b.copy()

In [30]:
a

array([11,  2,  3,  4])

In [31]:
b

array([11,  2,  3,  4])

In [32]:
a.T

array([11,  2,  3,  4])

In [33]:
a==b

array([ True,  True,  True,  True])

In [34]:
np.vstack((a,b))

array([[11,  2,  3,  4],
       [11,  2,  3,  4]])

In [35]:
np.hstack((a,b))

array([11,  2,  3,  4, 11,  2,  3,  4])

In [36]:
np.cos(a)


array([ 0.0044257 , -0.41614684, -0.9899925 , -0.65364362])

In [37]:
np.cos

<ufunc 'cos'>

In [38]:
np.sum(a)

20

In [39]:
np.median(a)

3.5

In [40]:
np.std(a)

3.5355339059327378

In [41]:
a

array([11,  2,  3,  4])

In [42]:
a=np.arange(1,10).reshape(3,3)

In [43]:
np.linalg.det(a)

0.0

In [52]:
a

array([ True,  True, False])

In [55]:
a=np.array([1,1,0],dtype=bool)
b=np.array([1,0,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True, False])

In [56]:
np.all(a==a)

True

In [57]:
np.logical_and(a,b)

array([ True, False, False])

In [58]:
np.all(a==a)

True

In [59]:
a=np.array([[1,2],[3,4]])

In [60]:
a.sum()

10

In [61]:
a.sum(axis=0)

array([4, 6])

In [62]:
a.sum(axis=1)

array([3, 7])

In [63]:
a.max()

4

In [64]:
a.argmax()

3

In [65]:
a.shape

(2, 2)

In [66]:
a=np.arange(1,10)

In [67]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a.shape




(9,)

In [69]:
a[:,np.newaxis].shape

(9, 1)

In [70]:
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

In [71]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])